name: DOS build

on:
  push:
    branches: [ main ]

jobs:
  build-windows:

    runs-on: windows-latest

    steps:
    - uses: actions/checkout@v2
    - name: Install winevdm
      run: choco install winevdm
    - name: Move build files
      run: |
        robocopy ${{ github.workspace }} C:\SRC /e
        exit 0
    - name: build
      run: |
          MAKEOPUS @FAST.INI
      working-directory: C:\SRC\OPUS\TOOLS